import styles from '@/styles/Home.module.css'
import Head from 'next/head'
import Image from 'next/image'


export default function Home() {
  return (
    <>
      <Head>
        <title>RJay Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        Hello, this is a work in progress app.
        Welcome to home page.
        Sign up to browse the rest of the pages.
      </main>
    </>
  )
}
